node 
{
  checkout scm
	dir('cloudd-registry')
	{
	  stage('Package') 
	  {
	     sh 'mvn clean package -DskipTests'
	  }
	}
  	dir('cloudd-registry')
	{
  		stage('Create Docker Image') 
  		{
    			docker.build("belalansari/cloud:2")
  		}
	}
	dir('cloudd-registry')
	{
		stage('Run Tests') 
  		{
			try 
			{  
				sh "mvn test"
				docker.withRegistry('https://hub.docker.com/', 'belalansari')
				{
					docker.build("belalansari/cloud:2").push()
				}
			} catch (error)
			{

			} 
		}	
	}
}
